/* GIMMY MODULE TABLES */

CREATE TABLE Candidate(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	center INT UNSIGNED NOT NULL,
	FOREIGN KEY (center) REFERENCES Center(id)
)Engine=InnoDB;

CREATE TABLE CandidateDetail(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	candidate INT UNSIGNED NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	age INT UNSIGNED NOT NULL,
	gender INT UNSIGNED NOT NULL,
	FOREIGN KEY (candidate) REFERENCES Candidate(id)
)Engine=InnoDB;

CREATE TABLE Room(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	center INT UNSIGNED NOT NULL,
	FOREIGN KEY (center) REFERENCES Center(id)
)Engine=InnoDB;

CREATE TABLE RoomDetail(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	room INT UNSIGNED NOT NULL,
	candidate INT UNSIGNED NOT NULL,
	FOREIGN KEY (room) REFERENCES Room(id),
	FOREIGN KEY (candidate) REFERENCES Candidate(id)
)Engine=InnoDB;

/* INSERTION */

